import mammoth from 'mammoth';
import type { BriefingContent, CreativeStructure, Variation, Scene, ABTest, Legend, CreativeType, Dont, Do as DoItem, HospedeProfile, PontoForteDetalhado } from '@/types/briefing';

/**
 * Parse a Seazone Spot DOCX briefing into structured BriefingContent.
 * The DOCX follows a rigid format generated by the briefing-spot-seazone skill.
 */
export async function parseDocx(buffer: ArrayBuffer): Promise<{
  spotName: string;
  city: string;
  content: Partial<BriefingContent>;
}> {
  const result = await mammoth.convertToHtml({ arrayBuffer: buffer });
  const html = result.value;

  // Create a simple DOM parser
  const sections = splitByHeaders(html);

  let spotName = '';
  let city = '';
  const criativos: BriefingContent['criativos'] = {};
  const legendas: Legend[] = [];

  // Extract spot name from first H1
  const h1Match = html.match(/<h1[^>]*>(.*?)<\/h1>/i);
  if (h1Match) {
    const fullTitle = stripHtml(h1Match[1]);
    const parts = fullTitle.split('—').map(s => s.trim());
    spotName = parts[0] || fullTitle;
    city = parts[1] || '';
  }

  // Try to parse creatives segmented by aba labels first (multi-type in one doc).
  // Falls back to single-type detection on the whole html if no aba markers found.
  const creativeBlocks = extractCreativeBlocks(html);
  let structures: CreativeStructure[] = [];
  let estatico_v2: ReturnType<typeof parseEstaticoV2> = null;
  if (creativeBlocks.length > 0) {
    for (const block of creativeBlocks) {
      const typeKey = block.type;
      if (typeKey === 'estatico') {
        // Try new format first
        const v2 = parseEstaticoV2(block.html);
        if (v2) {
          estatico_v2 = v2;
          (criativos as Record<string, unknown>).estatico_v2 = v2;
          continue;
        }
      }
      const blockStructures = parseStructures(block.html);
      if (blockStructures.length > 0) {
        (criativos as Record<string, CreativeType>)[typeKey] = { structures: blockStructures };
        if (structures.length === 0) structures = blockStructures;
      }
    }
  } else {
    const currentCreativeType = detectCreativeType(html);
    structures = parseStructures(html);
    if (structures.length > 0) {
      (criativos as Record<string, CreativeType>)[currentCreativeType] = { structures };
    }
  }
  void estatico_v2; // suppress unused-var lint

  // Parse legends
  const parsedLegends = parseLegends(html);

  // Parse structured fields from all abas
  const abas = parseAbas(html);

  return {
    spotName,
    city,
    content: {
      abas: {
        contexto: {
          spot_name: spotName,
          city,
          neighborhood: abas.contexto.neighborhood,
          region: abas.contexto.region,
          product_type: abas.contexto.product_type,
          stage: abas.contexto.stage,
          presenter: abas.contexto.presenter || 'Mônica',
          alvara_status: abas.contexto.alvara_status,
          positioning: abas.contexto.positioning,
          welcome_p1: abas.contexto.welcome_p1,
          welcome_p2: abas.contexto.welcome_p2,
          welcome_p3: abas.contexto.welcome_p3,
          notes: '',
        },
        dados_empreendimento: abas.dados_empreendimento,
        cronograma: abas.cronograma,
        informacoes_tecnicas: {
          typologies: abas.tecnicas.typologies,
          areas: abas.tecnicas.areas,
          total_units: abas.tecnicas.total_units,
          amenities: abas.tecnicas.amenities,
          construction_details: abas.tecnicas.construction_details,
          notes: '',
        },
        pontos_fortes: {
          selected: extractAllPontosFortes(structures),
          detalhados: abas.pontos_fortes_detalhados,
          notes: '',
        },
        dados_financeiros: {
          investment_from: abas.financeiros.investment_from,
          monthly_income: abas.financeiros.monthly_income,
          annual_income: abas.financeiros.annual_income,
          valorizacao_percentual: abas.financeiros.valorizacao_percentual,
          valorizacao_breakdown: abas.financeiros.valorizacao_breakdown,
          entrega_prevista: abas.financeiros.entrega_prevista,
          payment_conditions: abas.financeiros.payment_conditions,
          financing: abas.financeiros.financing,
          notes: '',
        },
        localizacao: {
          main_attraction: abas.localizacao.main_attraction,
          distance_to_attraction: abas.localizacao.distance_to_attraction,
          distances: abas.localizacao.distances,
          region_characteristics: abas.localizacao.region_characteristics,
          tourist_flow: abas.localizacao.tourist_flow,
          seasonality: abas.localizacao.seasonality,
          guest_profile: abas.localizacao.guest_profile,
          notes: '',
        },
        donts: abas.donts,
        dos: abas.dos,
        perfil_hospede: abas.perfil_hospede,
      },
      criativos,
      legendas: parsedLegends,
    },
  };
}

// ============================================================================
// Extraction for all informational abas (Contexto, Empreendimento, Cronograma,
// Técnicas, Pontos Fortes detalhados, Financeiros, Localização, Don'ts, Do's,
// Perfil do Hóspede). Criativos are handled elsewhere.
// ============================================================================
function parseAbas(html: string) {
  // Convert HTML to plain text with line breaks preserved
  const text = html
    .replace(/<(br|\/p|\/h[1-6]|\/div|\/li|\/tr)\s*\/?>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/[ \t]+/g, ' ')
    .replace(/\n\s*\n/g, '\n')
    .trim();

  // get('Label1', 'Label2', ...) → first non-empty value found
  const get = (...labels: string[]): string => {
    for (const label of labels) {
      const esc = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const re = new RegExp(`(?:^|\\n)\\s*${esc}\\s*[:—–-]\\s*(.+?)(?=\\n|$)`, 'i');
      const m = text.match(re);
      if (m && m[1].trim()) return m[1].trim();
    }
    return '';
  };

  // Brazilian money: "R$ 360.000" → 360000, "R$ 4.600,50" → 4600.50
  // Also handles "R$ 55 mil" → 55000, "R$ 296 mil" → 296000
  const money = (s: string): number => {
    if (!s) return 0;
    const hasMil = /\bmil\b/i.test(s);
    const cleaned = s.replace(/[^\d.,]/g, '');
    if (!cleaned) return 0;
    const normalized = cleaned.includes(',')
      ? cleaned.replace(/\./g, '').replace(',', '.')
      : cleaned.replace(/\./g, '');
    const n = parseFloat(normalized) || 0;
    return hasMil ? n * 1000 : n;
  };

  // First integer in string
  const num = (s: string): number => {
    if (!s) return 0;
    const m = s.match(/\d+/);
    return m ? parseInt(m[0]) : 0;
  };

  // Float (for percentages)
  const float = (s: string): number => {
    if (!s) return 0;
    const m = s.match(/([\d.,]+)/);
    if (!m) return 0;
    return parseFloat(m[1].replace(',', '.')) || 0;
  };

  // Comma / semicolon / pipe separated list
  const list = (s: string): string[] => {
    if (!s) return [];
    return s.split(/[,;|]/).map(x => x.trim()).filter(Boolean);
  };

  // Parse distances block
  const distances: { place: string; distance: string }[] = [];
  const distMatch = text.match(/Dist[âa]ncias?\s*[:—–-]?\s*\n([\s\S]*?)(?=\n\s*(?:[A-ZÀ-Ú][A-Za-zÀ-ú\s]{2,}\s*[:—–-]|ABA\s|ESTRUTURA\s|Legendas|H[12]|$))/i);
  if (distMatch) {
    const lines = distMatch[1].split('\n').map(l => l.trim()).filter(Boolean);
    for (const line of lines) {
      const m = line.match(/^[-•–—*]?\s*([^:—–]+?)\s*[:—–]\s*([0-9.,]+\s*(?:m|km|metros|quil[oô]metros)[^\n]*)$/i);
      if (m) distances.push({ place: m[1].trim(), distance: m[2].trim() });
    }
  }

  // Extract a block delimited by "ABA N — NAME" markers, returns block text
  const extractAba = (abaName: string): string => {
    const esc = abaName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const re = new RegExp(`ABA\\s*\\d+\\s*[—–-]\\s*${esc}([\\s\\S]*?)(?=ABA\\s*\\d+\\s*[—–-]|ESTRUTURA\\s*\\d+|Legendas para M[íi]dia|$)`, 'i');
    const m = text.match(re);
    return m ? m[1].trim() : '';
  };

  // Welcome paragraphs (3 paragraphs after "Bem-vindo ao" or from ABA 1 block)
  const welcomeBlock = text.match(/Bem-vindo ao [^\n]+\n([\s\S]*?)(?=ABA\s|Dados do Empreendimento|ESTRUTURA|$)/i);
  let welcome_p1 = '', welcome_p2 = '', welcome_p3 = '';
  if (welcomeBlock) {
    const paragraphs = welcomeBlock[1].split('\n').map(s => s.trim()).filter(s => s.length > 40);
    welcome_p1 = paragraphs[0] || '';
    welcome_p2 = paragraphs[1] || '';
    welcome_p3 = paragraphs[2] || '';
  }

  // ----- Pontos Fortes Detalhados -----
  // Format: "L — Localização\n[description]\n\nD — Distância..."
  const pontos_fortes_detalhados: PontoForteDetalhado[] = [];
  const pfBlock = extractAba('PONTOS FORTES');
  const validSiglas = ['C', 'L', 'D', 'Re', 'T', 'Pa', 'F', 'M', 'E', 'Va', 'Pe', 'Em', 'Ro', 'V'];
  if (pfBlock) {
    const pfItems = pfBlock.split(/(?=\n\s*[A-Z][a-z]?\s*[—–-]\s)/);
    for (const item of pfItems) {
      const hdr = item.match(/^\s*([A-Z][a-z]?)\s*[—–-]\s*([^\n]+)/);
      if (!hdr) continue;
      const sigla = hdr[1].trim();
      if (!validSiglas.includes(sigla)) continue;
      const nome = hdr[2].trim();
      const rest = item.slice(hdr[0].length).trim();
      const lines = rest.split('\n').map(s => s.trim()).filter(Boolean);
      const numeros = lines.filter(l => /R\$|^\d/.test(l) && l.length < 80);
      const descricao = lines.filter(l => !numeros.includes(l)).join(' ').trim();
      pontos_fortes_detalhados.push({ sigla, nome, descricao, numeros: numeros.length ? numeros : undefined });
    }
  }

  // ----- Don'ts -----
  const donts: Dont[] = [];
  const dontsBlock = extractAba("DON'TS") || extractAba('DONTS');
  if (dontsBlock) {
    const items = dontsBlock.split(/(?=\n?\s*Don'?t\s*\d+\s*:)/i).filter(s => /Don'?t/i.test(s));
    for (const item of items) {
      const titulo = (item.match(/Don'?t\s*\d+\s*:\s*([^\n]+)/i)?.[1] || '').trim();
      const tag = (item.match(/\bTag\s*:\s*([^\n]+)/i)?.[1] || '').trim();
      const descricao = (item.match(/\bDescri[cç][ãa]o\s*:\s*([^\n]+)/i)?.[1] || '').trim();
      const itensRaw = (item.match(/\bItens\s*:\s*([^\n]+)/i)?.[1] || '').trim();
      const itens = itensRaw ? list(itensRaw) : undefined;
      const nota = (item.match(/\bNota\s*:\s*([^\n]+)/i)?.[1] || '').trim();
      if (titulo) {
        donts.push({
          titulo,
          tag: tag || 'Não mencionar',
          descricao: descricao || undefined,
          itens,
          nota: nota || undefined,
        });
      }
    }
  }

  // ----- Do's -----
  const dos: DoItem[] = [];
  const dosBlock = extractAba("DO'S") || extractAba('DOS');
  if (dosBlock) {
    const items = dosBlock.split(/(?=\n?\s*Do\s*\d+\s*:)/i).filter(s => /\bDo\s*\d+\s*:/i.test(s));
    for (const item of items) {
      const titulo = (item.match(/Do\s*\d+\s*:\s*([^\n]+)/i)?.[1] || '').trim();
      const tag = (item.match(/\bTag\s*:\s*([^\n]+)/i)?.[1] || '').trim();
      const descricao = (item.match(/\bDescri[cç][ãa]o\s*:\s*([^\n]+)/i)?.[1] || '').trim();
      const subRaw = (item.match(/\bSub-itens\s*:\s*([^\n]+)/i)?.[1] || '').trim();
      const sub_itens = subRaw ? list(subRaw) : undefined;
      if (titulo) {
        dos.push({
          titulo,
          tag: tag || 'Reforçar',
          descricao: descricao || '',
          sub_itens,
        });
      }
    }
  }

  // ----- Perfil do Hóspede -----
  const perfilBlock = extractAba('PERFIL DO HÓSPEDE') || extractAba('PERFIL DO HOSPEDE');
  let perfil_hospede: BriefingContent['abas']['perfil_hospede'] = undefined;
  if (perfilBlock) {
    const intro = (perfilBlock.match(/\bIntrodu[cç][ãa]o\s*:\s*([^\n]+)/i)?.[1] || '').trim();
    const descricaoPerfilBlock = (perfilBlock.match(/\bDescri[cç][ãa]o\s*:\s*([^\n]+)/i)?.[1] || '').trim();
    const perfis: HospedeProfile[] = [];
    const perfilItems = perfilBlock.split(/(?=\n?\s*Perfil\s*\d+\s*:)/i).filter(s => /Perfil\s*\d+\s*:/i.test(s));
    for (const item of perfilItems) {
      const nome = (item.match(/Perfil\s*\d+\s*:\s*([^\n]+)/i)?.[1] || '').trim();
      const tag = (item.match(/\bTag\s*:\s*([^\n]+)/i)?.[1] || '').trim();
      // "Descrição:" within a perfil item (match the LAST one since the outer intro also has Descrição)
      const descricoes = Array.from(item.matchAll(/\bDescri[cç][ãa]o\s*:\s*([^\n]+)/gi));
      const descricao = (descricoes.length > 0 ? descricoes[descricoes.length - 1][1] : '').trim();
      if (nome) {
        perfis.push({ nome, tag: tag || 'Perfil Principal', descricao });
      }
    }
    const destinoBlock = extractAba('CARACTERÍSTICAS DO DESTINO') || extractAba('CARACTERISTICAS DO DESTINO');
    const destino = {
      regiao: '', perfil: '', praia: '', infraestrutura: '',
    };
    if (destinoBlock) {
      const getFromDest = (label: string): string => {
        const esc = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const re = new RegExp(`(?:^|\\n)\\s*${esc}\\s*[:—–-]\\s*(.+?)(?=\\n|$)`, 'i');
        const m = destinoBlock.match(re);
        return m ? m[1].trim() : '';
      };
      destino.regiao = getFromDest('Região') || getFromDest('Regiao');
      destino.perfil = getFromDest('Perfil');
      destino.praia = getFromDest('Praia') || getFromDest('Paisagem') || getFromDest('Natureza');
      destino.infraestrutura = getFromDest('Infraestrutura');
    }
    perfil_hospede = { intro, descricao: descricaoPerfilBlock, perfis, destino };
  }

  // ----- Dados do Empreendimento -----
  const empBlock = extractAba('DADOS DO EMPREENDIMENTO');
  let dados_empreendimento: BriefingContent['abas']['dados_empreendimento'] = undefined;
  if (empBlock) {
    const getFromEmp = (label: string): string => {
      const esc = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const re = new RegExp(`(?:^|\\n)\\s*${esc}\\s*[:—–-]\\s*(.+?)(?=\\n|$)`, 'i');
      const m = empBlock.match(re);
      return m ? m[1].trim() : '';
    };
    const metragens = getFromEmp('Metragens');
    const metragem_min = metragens ? num(metragens.split(/[ae–—-]/)[0]) : 0;
    const metragem_max = metragens ? num(metragens.split(/[ae–—-]/).pop() || '0') : 0;
    dados_empreendimento = {
      quantidade_opcoes: num(getFromEmp('Quantidade de opções') || getFromEmp('Cotas')),
      pavimentos: getFromEmp('Pavimentos'),
      tipologias_count: num(getFromEmp('Tipologias')),
      metragem_min,
      metragem_max,
      vagas_garagem: getFromEmp('Vagas de garagem'),
      modalidade_aprovacao: getFromEmp('Modalidade de aprovação'),
      administrador_obras: getFromEmp('Administrador de obras'),
      arquiteto: getFromEmp('Arquiteto'),
      cotas_marketplace: num(getFromEmp('Cotas disponíveis no Marketplace')),
    };
  }

  // ----- Cronograma -----
  const cronBlock = extractAba('CRONOGRAMA DE OBRAS') || extractAba('CRONOGRAMA');
  let cronograma: BriefingContent['abas']['cronograma'] = undefined;
  if (cronBlock) {
    const getFromCron = (label: string): string => {
      const esc = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const re = new RegExp(`(?:^|\\n)\\s*${esc}\\s*[:—–-]\\s*(.+?)(?=\\n|$)`, 'i');
      const m = cronBlock.match(re);
      return m ? m[1].trim() : '';
    };
    cronograma = {
      inicio_vendas: getFromCron('Início das vendas'),
      fechamento_grupo: getFromCron('Fechamento do grupo'),
      inicio_obra: getFromCron('Início da obra'),
      entrega_obra: getFromCron('Entrega da obra'),
      fase_projeto: getFromCron('Fase do projeto'),
    };
  }

  return {
    contexto: {
      neighborhood: get('Bairro'),
      region: get('Região', 'Regiao'),
      product_type: get('Categoria', 'Tipo de produto'),
      stage: get('Estágio', 'Estagio', 'Fase'),
      presenter: get('Apresentadora', 'Host'),
      alvara_status: get('Alvará', 'Alvara'),
      positioning: get('Posicionamento'),
      welcome_p1,
      welcome_p2,
      welcome_p3,
    },
    dados_empreendimento,
    cronograma,
    tecnicas: {
      typologies: list(get('Tipologias')),
      areas: list(get('Áreas', 'Areas', 'Metragens')),
      total_units: num(get('Total de unidades', 'Unidades', 'Número de unidades', 'Numero de unidades')),
      amenities: list(get('Amenidades', 'Amenities', 'Áreas Comuns', 'Areas Comuns', 'Lazer')),
      construction_details: get('Detalhes construtivos', 'Detalhes', 'Construção'),
    },
    pontos_fortes_detalhados: pontos_fortes_detalhados.length > 0 ? pontos_fortes_detalhados : undefined,
    financeiros: {
      investment_from: money(get('Investimento a partir de', 'Investimento', 'Ticket de entrada', 'Ticket', 'Valor a partir de')),
      monthly_income: money(get('Rendimento líquido mensal', 'Rendimento mensal estimado', 'Rendimento mensal', 'RE Mensal', 'Renda mensal')),
      annual_income: money(get('Rendimento líquido anual', 'Rendimento anual estimado', 'Rendimento anual', 'RE Anual', 'Renda anual')),
      valorizacao_percentual: float(get('Valorização em 3 anos', 'Valorização')),
      valorizacao_breakdown: get('Breakdown da valorização', 'Breakdown'),
      entrega_prevista: get('Entrega prevista', 'Entrega da obra'),
      payment_conditions: get('Condições de pagamento', 'Condições', 'Condicoes'),
      financing: get('Financiamento'),
    },
    localizacao: {
      main_attraction: get('Principal atrativo', 'Atrativo principal'),
      distance_to_attraction: get('Distância do principal atrativo', 'Distância do atrativo'),
      distances,
      region_characteristics: get('Características da região', 'Caracteristicas da regiao'),
      tourist_flow: get('Fluxo turístico', 'Fluxo turistico'),
      seasonality: get('Sazonalidade'),
      guest_profile: get('Perfil do hóspede geral', 'Perfil geral'),
    },
    donts: donts.length > 0 ? donts : undefined,
    dos: dos.length > 0 ? dos : undefined,
    perfil_hospede,
  };
}

function detectCreativeType(html: string): string {
  const lower = html.toLowerCase();
  // Check for disruptivo first (more specific)
  if (lower.includes('disruptivo') && lower.includes('narrad')) return 'disruptivo_narrado';
  if (lower.includes('disruptivo')) return 'disruptivo_apresentadora';
  if (lower.includes('narrad') || lower.includes('narração')) return 'video_narrado';
  if (lower.includes('apresentadora') || lower.includes('locução')) return 'video_apresentadora';
  if (lower.includes('estático') || lower.includes('estatico')) return 'estatico';
  return 'video_apresentadora'; // default
}

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, '').trim();
}

function splitByHeaders(html: string): string[] {
  return html.split(/(?=<h[12][^>]*>)/i).filter(s => s.trim());
}

function parseStructures(html: string): CreativeStructure[] {
  const structures: CreativeStructure[] = [];

  // Split by "ESTRUTURA" labels
  const estruturaRegex = /ESTRUTURA\s*\d+/gi;
  const parts = html.split(estruturaRegex);

  // Skip the first part (before first ESTRUTURA)
  for (let i = 1; i < parts.length; i++) {
    const part = parts[i];
    const structure = parseOneStructure(part);
    if (structure) structures.push(structure);
  }

  // If no ESTRUTURA labels found, try to parse the whole thing as one structure
  if (structures.length === 0) {
    const structure = parseOneStructure(html);
    if (structure && structure.variations.length > 0) {
      structures.push(structure);
    }
  }

  return structures;
}

function parseOneStructure(html: string): CreativeStructure | null {
  // Extract structure name from first H1 after ESTRUTURA label
  const nameMatch = html.match(/<h1[^>]*>(.*?)<\/h1>/i);
  const name = nameMatch ? stripHtml(nameMatch[1]) : 'Estrutura';

  // Extract pontos fortes from badges or text like "L | D | Re | T"
  const pontosFortes = extractPontosFromText(html);

  // Extract logic
  let logic = '';
  const logicMatch = html.match(/Lógica da Estrutura<\/[^>]+>(.*?)(?=<h[12]|TERRITÓRIO|V\d\s*—|<table)/is);
  if (logicMatch) {
    logic = stripHtml(logicMatch[1]).trim();
  }

  // Extract territory (disruptivo only)
  let territory: string[] = [];
  const territoryMatch = html.match(/Território Criativo<\/[^>]+>(.*?)(?=<h[12]|V\d\s*—|<table)/is);
  if (territoryMatch) {
    const items = stripHtml(territoryMatch[1]).split(/[•\n]/).filter(s => s.trim());
    territory = items.map(s => s.trim()).filter(Boolean);
  }

  // Extract focus central (disruptivo only)
  let focusCentral = '';
  const focusMatch = html.match(/Foco central[:\s]*(.*?)(?=<\/p>|<br|Pontos fortes)/is);
  if (focusMatch) {
    focusCentral = stripHtml(focusMatch[1]).trim();
  }

  // Parse variations
  const variations = parseVariations(html);

  // Parse AB tests
  const abTests = parseABTests(html);

  if (!name && variations.length === 0) return null;

  return {
    name,
    pontos_fortes: pontosFortes,
    logic,
    focus_central: focusCentral || undefined,
    territory: territory.length > 0 ? territory : undefined,
    variations,
    ab_tests: abTests,
  };
}

function parseVariations(html: string): Variation[] {
  const variations: Variation[] = [];

  // Match variation headers: "V1 — description" or "V1"
  const varRegex = /V(\d)\s*(?:—|–|-)\s*(.*?)(?=<\/|$)/gi;
  const varParts = html.split(/(?=V[1-5]\s*(?:—|–|-))/);

  for (const part of varParts) {
    const numMatch = part.match(/^V([1-5])\s*(?:—|–|-)\s*/);
    if (!numMatch) continue;

    const varNum = parseInt(numMatch[1]);

    // Extract hypothesis
    let hypothesis = '';
    const hypMatch = part.match(/Hipótese[:\s]*(.*?)(?=<|Duração|\n)/i);
    if (hypMatch) hypothesis = stripHtml(hypMatch[1]).trim();

    // Extract duration
    let duration: '10-20' | '30-40' | '40-60' = '30-40';
    const durMatch = part.match(/Duração[:\s]*(\d+)[–-](\d+)/i);
    if (durMatch) {
      const d = parseInt(durMatch[1]);
      if (d <= 20) duration = '10-20';
      else if (d <= 40) duration = '30-40';
      else duration = '40-60';
    }

    // Extract pontos fortes
    const pontosFortes = extractPontosFromText(part);

    // Parse scenes from tables
    const scenes = parseScenesFromTable(part);

    if (scenes.length > 0 || hypothesis) {
      variations.push({
        variation_number: varNum,
        hypothesis,
        duration,
        pontos_fortes: pontosFortes,
        scenes,
      });
    }
  }

  return variations;
}

function parseScenesFromTable(html: string): Scene[] {
  const scenes: Scene[] = [];

  // Find tables in this section
  const tableMatch = html.match(/<table[^>]*>(.*?)<\/table>/is);
  if (!tableMatch) return scenes;

  const tableHtml = tableMatch[1];
  const rows = tableHtml.match(/<tr[^>]*>(.*?)<\/tr>/gis) || [];

  for (let i = 1; i < rows.length; i++) { // skip header row
    const cells = rows[i]?.match(/<td[^>]*>(.*?)<\/td>/gis) || [];
    if (cells.length >= 4) {
      const num = parseInt(stripHtml(cells[0] || '')) || i;
      const cena = stripHtml(cells[1] || '');
      const lettering = stripHtml(cells[2] || '') || '—';
      const locucao = stripHtml(cells[3] || '');

      scenes.push({
        scene_number: num,
        scene_name: `Cena ${num}`,
        visual_sequence: cena,
        copy_direction: locucao,
        example: locucao,
        lettering,
      });
    }
  }

  return scenes;
}

function parseABTests(html: string): ABTest[] {
  const tests: ABTest[] = [];

  const testRegex = /Teste\s*(\d+)[:\s]*(.*?)(?=Teste\s*\d|<h|$)/gis;
  let match;

  while ((match = testRegex.exec(html)) !== null) {
    const testNum = parseInt(match[1]);
    const content = stripHtml(match[2]);

    // Parse "V1 (desc) × V2 (desc)" format
    const vsMatch = content.match(/V(\d).*?[×x]\s*V(\d)/i);
    if (vsMatch) {
      const va = parseInt(vsMatch[1]);
      const vb = parseInt(vsMatch[2]);

      // Extract hypotheses
      const hypA = content.match(/(?:Hipótese\s*)?(?:VARIAÇÃO\s*\d+[:\s]*)?(.*?)(?:\s*[×x])/i);
      const hypB = content.match(/[×x]\s*(?:Hipótese\s*)?(?:VARIAÇÃO\s*\d+[:\s]*)?(.*?)$/i);

      tests.push({
        test_number: testNum,
        variation_a: va,
        variation_b: vb,
        hypothesis_a: hypA ? hypA[1].trim() : `V${va}`,
        hypothesis_b: hypB ? hypB[1].trim() : `V${vb}`,
      });
    }
  }

  return tests;
}

function parseLegends(html: string): Legend[] {
  // Simplified legend parsing - extract text blocks after "Legendas"
  const legends: Legend[] = [];

  const legendSection = html.match(/Legendas para Mídia Paga(.*?)$/is);
  if (!legendSection) return legends;

  const content = legendSection[1];

  // Try to find "Versão Completa" and "Versão Enxuta" blocks
  const fullMatch = content.match(/Versão Completa(.*?)(?=Versão Enxuta|$)/is);
  const shortMatch = content.match(/Versão Enxuta(.*?)$/is);

  const legend: Legend = {
    creative_type: 'video_apresentadora',
    full_headline: '',
    full_body: '',
    full_financial: '',
    full_institutional: '',
    full_cta: '',
    short_headline: '',
    short_body: '',
    short_location: '',
    short_cta: '',
  };

  if (fullMatch) {
    const lines = stripHtml(fullMatch[1]).split('\n').map(s => s.trim()).filter(Boolean);
    if (lines.length === 1) {
      // Single paragraph (texto corrido): use as headline, leave body/cta empty to avoid duplication
      legend.full_headline = lines[0];
    } else if (lines.length === 2) {
      legend.full_headline = lines[0];
      legend.full_cta = lines[1];
    } else if (lines.length >= 3) {
      legend.full_headline = lines[0];
      legend.full_body = lines.slice(1, -1).join('\n');
      legend.full_cta = lines[lines.length - 1];
    }
  }

  if (shortMatch) {
    const lines = stripHtml(shortMatch[1]).split('\n').map(s => s.trim()).filter(Boolean);
    if (lines.length === 1) {
      legend.short_headline = lines[0];
    } else if (lines.length === 2) {
      legend.short_headline = lines[0];
      legend.short_cta = lines[1];
    } else if (lines.length >= 3) {
      legend.short_headline = lines[0];
      legend.short_body = lines.slice(1, -1).join('\n');
      legend.short_cta = lines[lines.length - 1];
    }
  }

  if (legend.full_headline || legend.short_headline) {
    legends.push(legend);
  }

  return legends;
}

function extractPontosFromText(text: string): string[] {
  const validPontos = ['C', 'L', 'D', 'Re', 'T', 'Pa', 'F', 'M', 'E', 'Va', 'Pe', 'Em', 'Ro', 'V'];
  const found: string[] = [];

  // Look for patterns like "L | D | Re | T" or badge-style inline text
  const pipeMatch = text.match(/(?:Pontos fortes[:\s]*)?([A-Z][a-z]?(?:\s*\|\s*[A-Z][a-z]?)+)/);
  if (pipeMatch) {
    const parts = pipeMatch[1].split('|').map(s => s.trim());
    for (const p of parts) {
      if (validPontos.includes(p) && !found.includes(p)) {
        found.push(p);
      }
    }
  }

  return found;
}

function extractAllPontosFortes(structures: CreativeStructure[]): string[] {
  const all = new Set<string>();
  for (const s of structures) {
    for (const p of s.pontos_fortes) all.add(p);
    for (const v of s.variations) {
      for (const p of v.pontos_fortes) all.add(p);
    }
  }
  return Array.from(all);
}

// ============================================================================
// Split HTML into per-type creative blocks using "ABA N — CRIATIVOS <TIPO>" markers.
// Returns [] when no markers are found (caller falls back to single-type mode).
// ============================================================================
interface CreativeBlock {
  type: 'estatico' | 'video_apresentadora' | 'video_narrado' | 'disruptivo_apresentadora' | 'disruptivo_narrado';
  html: string;
}

function extractCreativeBlocks(html: string): CreativeBlock[] {
  // Patterns in the label of the ABA heading, in priority order (more specific first)
  const markers: { type: CreativeBlock['type']; re: RegExp }[] = [
    { type: 'disruptivo_narrado',       re: /CRIATIVOS?\s*[—–-]?\s*DISRUPTIVO\s+NARRAD[OA]/i },
    { type: 'disruptivo_apresentadora', re: /CRIATIVOS?\s*[—–-]?\s*DISRUPTIVO\s+APRESENTADORA/i },
    { type: 'video_narrado',            re: /CRIATIVOS?\s*[—–-]?\s*V[ÍI]DEO\s+NARRAD[OA]/i },
    { type: 'video_apresentadora',      re: /CRIATIVOS?\s*[—–-]?\s*V[ÍI]DEO\s+APRESENTADORA/i },
    { type: 'estatico',                 re: /CRIATIVOS?\s*[—–-]?\s*EST[ÁA]TICO/i },
  ];

  // Find ALL matches of "ABA N — CRIATIVOS ..." in order of appearance in the document
  const abaRe = /ABA\s*\d+\s*[—–-]\s*([^<\n]+?)(?=<|\n|$)/gi;
  const hits: { index: number; type: CreativeBlock['type'] }[] = [];
  let m: RegExpExecArray | null;
  while ((m = abaRe.exec(html)) !== null) {
    const label = m[1];
    for (const { type, re } of markers) {
      if (re.test(label)) {
        hits.push({ index: m.index, type });
        break;
      }
    }
  }

  if (hits.length === 0) return [];

  // Build blocks from each hit to the next ABA/legendas marker
  const blocks: CreativeBlock[] = [];
  const endPattern = /ABA\s*\d+\s*[—–-]|Legendas para M[íi]dia/gi;
  for (let i = 0; i < hits.length; i++) {
    const start = hits[i].index;
    // Find the next aba/legend marker after this hit
    endPattern.lastIndex = start + 1;
    const nextMatch = endPattern.exec(html);
    const end = nextMatch ? nextMatch.index : html.length;
    blocks.push({ type: hits[i].type, html: html.slice(start, end) });
  }
  return blocks;
}

// ============================================================================
// Parser do formato NOVO de estático (peças fixas, sem cenas).
// Retorna null se não achar o formato novo no bloco.
// ============================================================================
function parseEstaticoV2(html: string): {
  label?: string;
  subtitle?: string;
  global_guidelines: string[];
  structures: Array<{
    name: string;
    base_image: string;
    base_image_description: string;
    variations: Array<{
      variation_number: number;
      hypothesis: string;
      frase_destaque: string;
      textos_fixos: string[];
    }>;
    ab_tests: Array<{
      test_number: number;
      kind: 'AB' | 'ABC';
      hypotheses: string[];
      variations: number[];
    }>;
  }>;
  cross_test?: { hypothesis: string; variation_number: number; objective: string };
} | null {
  // Convert to plain text preserving line breaks
  const text = html
    .replace(/<(br|\/p|\/h[1-6]|\/div|\/li|\/tr)\s*\/?>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/[ \t]+/g, ' ')
    .trim();

  // Marker: "Imagem base:" OR "Frase de destaque:" OR "Textos fixos da peça:"
  if (!/Imagem\s*base\s*:/i.test(text) && !/Frase\s*de\s*destaque/i.test(text)) {
    return null;
  }

  // Global guidelines: after "DIRETRIZES OBRIGAT" until first "ESTRUTURA"
  const global_guidelines: string[] = [];
  const dgMatch = text.match(/DIRETRIZES\s+OBRIGAT[ÓO]RIAS[^\n]*\n([\s\S]*?)(?=ESTRUTURA\s*\d)/i);
  if (dgMatch) {
    const lines = dgMatch[1].split('\n').map(l => l.trim()).filter(Boolean);
    for (const line of lines) {
      // Strip bullet markers
      const cleaned = line.replace(/^[•●\-*·\u2022]+\s*/, '').trim();
      if (cleaned && !/^Estrutura/i.test(cleaned)) {
        global_guidelines.push(cleaned);
      }
    }
  }

  // Structures: split by "Estrutura N" headings (not case-sensitive)
  const structRegex = /Estrutura\s+\d+/gi;
  const structParts: string[] = [];
  const matchesArr: RegExpExecArray[] = [];
  let m: RegExpExecArray | null;
  while ((m = structRegex.exec(text)) !== null) matchesArr.push(m);

  for (let i = 0; i < matchesArr.length; i++) {
    const start = matchesArr[i].index;
    const end = i + 1 < matchesArr.length ? matchesArr[i + 1].index : (() => {
      const xt = text.slice(start).search(/Teste\s*Extra|Legendas|ABA\s*\d+\s*[—–-]/i);
      return xt > 0 ? start + xt : text.length;
    })();
    structParts.push(text.slice(start, end));
  }

  const structures = structParts.map(parseEstaticoStructure).filter(Boolean) as NonNullable<ReturnType<typeof parseEstaticoStructure>>[];

  // Cross test (Teste Extra — Impacto da Imagem)
  let cross_test: { hypothesis: string; variation_number: number; objective: string } | undefined;
  const crossMatch = text.match(/Teste\s*Extra\s*[—–-]?\s*Impacto\s+da\s+Imagem([\s\S]*?)(?=ABA\s*\d+\s*[—–-]|Legendas|$)/i);
  if (crossMatch) {
    const block = crossMatch[1];
    const hypMatch = block.match(/Hip[óo]tese[^:]*:\s*([^\n]+)/i);
    const varMatch = block.match(/Varia[çc][ãa]o\s*(\d+)/i);
    const objMatch = block.match(/Objetivo[^:]*:\s*([\s\S]+?)(?=\n\s*\n|ABA|Legendas|$)/i);
    cross_test = {
      hypothesis: (hypMatch?.[1] || '').trim(),
      variation_number: varMatch ? parseInt(varMatch[1]) : 1,
      objective: (objMatch?.[1] || 'Identificar qual tipo de imagem gera mais impacto para a mesma mensagem principal.').trim(),
    };
  }

  if (structures.length === 0) return null;

  return {
    label: undefined,
    subtitle: 'Peças estáticas para feed e stories',
    global_guidelines,
    structures,
    cross_test,
  };
}

function parseEstaticoStructure(chunk: string): {
  name: string;
  base_image: string;
  base_image_description: string;
  variations: Array<{ variation_number: number; hypothesis: string; frase_destaque: string; textos_fixos: string[] }>;
  ab_tests: Array<{ test_number: number; kind: 'AB' | 'ABC'; hypotheses: string[]; variations: number[] }>;
} | null {
  const nameMatch = chunk.match(/Estrutura\s+(\d+)/i);
  if (!nameMatch) return null;
  const name = `Estrutura ${nameMatch[1]}`;

  const baseImgMatch = chunk.match(/Imagem\s*base\s*:\s*([^\n]+)/i);
  const base_image = (baseImgMatch?.[1] || '').trim();

  // description: the lines right after "IMAGEM BASE" heading or first paragraph after "Imagem base: X"
  let base_image_description = '';
  const descBlock = chunk.match(/(?:IMAGEM\s*BASE|Imagem\s*base\s*:\s*[^\n]+)\s*\n([\s\S]*?)(?=V\s*\d|$)/i);
  if (descBlock) {
    const lines = descBlock[1].split('\n').map(l => l.trim()).filter(Boolean);
    const candidate = lines.find(l => /\bvaria[çc][ãa]o/i.test(l) || /apresentar\s+imagens/i.test(l));
    base_image_description = candidate || lines.slice(0, 2).join(' ');
  }

  // Variations
  const variations: Array<{ variation_number: number; hypothesis: string; frase_destaque: string; textos_fixos: string[] }> = [];
  const varRe = /V\s*(\d)\s*\n([\s\S]*?)(?=\nV\s*\d\s*\n|Testes?\s*A\/B|$)/g;
  let vm: RegExpExecArray | null;
  while ((vm = varRe.exec(chunk)) !== null) {
    const variation_number = parseInt(vm[1]);
    const body = vm[2];
    const hypM = body.match(/Hip[óo]tese\s*:\s*([^\n]+)/i);
    const fdM = body.match(/Frase\s*de\s*destaque\s*:\s*([\s\S]*?)(?=\n\s*\n|Textos\s*fixos|$)/i);
    const tfM = body.match(/Textos\s*fixos\s*da\s*pe[çc]a\s*:\s*([\s\S]*?)(?=\n\s*V\s*\d|Testes|$)/i);
    const textos_fixos: string[] = [];
    if (tfM) {
      const lines = tfM[1].split('\n').map(l => l.replace(/^[•●\-*·\u2022]+\s*/, '').trim()).filter(Boolean);
      textos_fixos.push(...lines);
    }
    variations.push({
      variation_number,
      hypothesis: (hypM?.[1] || '').trim(),
      frase_destaque: (fdM?.[1] || '').trim(),
      textos_fixos,
    });
  }

  // AB Tests
  const ab_tests: Array<{ test_number: number; kind: 'AB' | 'ABC'; hypotheses: string[]; variations: number[] }> = [];
  const abBlock = chunk.match(/Testes?\s*A\/B([\s\S]*?)(?=Estrutura\s+\d|Teste\s*Extra|$)/i);
  if (abBlock) {
    const testRe = /Teste\s*(\d+)[^\n]*?(A\/B\/C|A\/B)([\s\S]*?)(?=Teste\s*\d|$)/gi;
    let tm: RegExpExecArray | null;
    while ((tm = testRe.exec(abBlock[1])) !== null) {
      const test_number = parseInt(tm[1]);
      const kind: 'AB' | 'ABC' = /ABC/i.test(tm[2]) ? 'ABC' : 'AB';
      const body = tm[3];
      const hypothesis_matches = Array.from(body.matchAll(/Hip[óo]tese\s*VARIA[ÇC][ÃA]O\s*(\d+)\s*:\s*([^\n×x]+)/gi));
      const variations = hypothesis_matches.map(h => parseInt(h[1]));
      const hypotheses = hypothesis_matches.map(h => h[2].trim());
      if (variations.length >= 2) {
        ab_tests.push({ test_number, kind, hypotheses, variations });
      }
    }
  }

  if (variations.length === 0) return null;

  return { name, base_image, base_image_description, variations, ab_tests };
}
